services:
  smokeping:
    image: linuxserver/smokeping@sha256:8dd68d8483cbd461b0d32365254c8fd59778efb9dc8064517f85dc27eae41433
    container_name: smokeping
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=UTC
    volumes:
      - ./smokeping/config:/config
      - ./smokeping/data:/data
      - ./smokeping/etc/config:/etc/smokeping/config
      - ./smokeping/etc/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    ports:
      - 8099:80
    mem_limit: 4096m
    restart: unless-stopped