services:
  smokeping:
    image: linuxserver/smokeping@sha256:210b9d97e376bd81faf86d50f06358dd7a0090be115b2af280d76b5abbcccb6e
    container_name: smokeping
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=UTC
    volumes:
      - ./smokeping/config:/config
      - ./smokeping/data:/data
      - ./smokeping/etc/config:/etc/smokeping/config
      - ./smokeping/etc/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    ports:
      - 8099:80
    mem_limit: 4096m
    restart: unless-stopped